Base firebase
muadev/tendercats pull request #12
Opened 2021-12-13 16:44 UTC by nicolaslarrea

paquetes y configuración básica para conectar con firebase real time DB.

Closes #4

2021-12-14 16:15 UTC, tesitura approved these changes

2021-12-14 18:19 UTC, mauriciopasquier requested changes
Me gustaría mergear una vez que resolvamos el tema de los tests, no puede ser que agregar una librería rompa todo. Además hay que acostumbrarse a correrlos antes de pushear :P (otro punto a revisar con actions o hooks @tesitura)

2021-12-14 18:19 UTC, mauriciopasquier commented on android/app/build.gradle
> +apply plugin: 'com.google.gms.google-services'
Podemos agregar comentarios en estos archivos crípticos para saber que esto es de firebase?

2021-12-14 18:19 UTC, mauriciopasquier commented on android/build.gradle
> +        classpath 'com.google.gms:google-services:4.3.10'
Acá también

2021-12-15 21:26 UTC, mauriciopasquier approved these changes

2021-12-15 21:28 UTC, merged